
package midas.nmp.com.mx;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConciliacionPagoOnlineService", targetNamespace = "urn:mx.com.nmp.midas", wsdlLocation = "http://localhost:9010/midas-web/services/ConciliacionPagoOnlineService?wsdl")
public class ConciliacionPagoOnlineService
    extends Service
{

    private final static URL CONCILIACIONPAGOONLINESERVICE_WSDL_LOCATION;
    private final static WebServiceException CONCILIACIONPAGOONLINESERVICE_EXCEPTION;
    private final static QName CONCILIACIONPAGOONLINESERVICE_QNAME = new QName("urn:mx.com.nmp.midas", "ConciliacionPagoOnlineService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9010/midas-web/services/ConciliacionPagoOnlineService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONCILIACIONPAGOONLINESERVICE_WSDL_LOCATION = url;
        CONCILIACIONPAGOONLINESERVICE_EXCEPTION = e;
    }

    public ConciliacionPagoOnlineService() {
        super(__getWsdlLocation(), CONCILIACIONPAGOONLINESERVICE_QNAME);
    }

    public ConciliacionPagoOnlineService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONCILIACIONPAGOONLINESERVICE_QNAME, features);
    }

    public ConciliacionPagoOnlineService(URL wsdlLocation) {
        super(wsdlLocation, CONCILIACIONPAGOONLINESERVICE_QNAME);
    }

    public ConciliacionPagoOnlineService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONCILIACIONPAGOONLINESERVICE_QNAME, features);
    }

    public ConciliacionPagoOnlineService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConciliacionPagoOnlineService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConciliacionPagoOnlineServicePortType
     */
    @WebEndpoint(name = "ConciliacionPagoOnlineServiceHttpPort")
    public ConciliacionPagoOnlineServicePortType getConciliacionPagoOnlineServiceHttpPort() {
        return super.getPort(new QName("urn:mx.com.nmp.midas", "ConciliacionPagoOnlineServiceHttpPort"), ConciliacionPagoOnlineServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConciliacionPagoOnlineServicePortType
     */
    @WebEndpoint(name = "ConciliacionPagoOnlineServiceHttpPort")
    public ConciliacionPagoOnlineServicePortType getConciliacionPagoOnlineServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:mx.com.nmp.midas", "ConciliacionPagoOnlineServiceHttpPort"), ConciliacionPagoOnlineServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONCILIACIONPAGOONLINESERVICE_EXCEPTION!= null) {
            throw CONCILIACIONPAGOONLINESERVICE_EXCEPTION;
        }
        return CONCILIACIONPAGOONLINESERVICE_WSDL_LOCATION;
    }

}
