
package midas.nmp.com.mx;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import mx.com.montedepiedad.servicios.nmp.schema.nmpconciliacionpagoonline.ArrayOfMovimientoConciliacionNocturna;
import mx.com.montedepiedad.servicios.nmp.schema.nmpconciliacionpagoonline.ArrayOfMovimientoProveedorTransaccional;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConciliacionPagoOnlineServicePortType", targetNamespace = "urn:mx.com.nmp.midas")
@XmlSeeAlso({
    midas.nmp.com.mx.ObjectFactory.class,
    mx.com.montedepiedad.servicios.nmp.schema.nmpconciliacionpagoonline.ObjectFactory.class,
    mx.com.montedepiedad.servicios.nmp.schema.nmpstandardmessage.ObjectFactory.class,
    mx.com.montedepiedad.servicios.nmp.services.nmpconciliacionpagoonline.ObjectFactory.class
})
public interface ConciliacionPagoOnlineServicePortType {


    /**
     * 
     * @param fechaFin
     * @param fechaInicio
     * @return
     *     returns mx.com.montedepiedad.servicios.nmp.schema.nmpconciliacionpagoonline.ArrayOfMovimientoConciliacionNocturna
     * @throws ConciliacionPagoOnlineFaultMessage
     */
    @WebMethod
    @WebResult(name = "movimientos", targetNamespace = "urn:mx.com.nmp.midas")
    @RequestWrapper(localName = "obtenerMovimientosConciliacionNocturna", targetNamespace = "urn:mx.com.nmp.midas", className = "midas.nmp.com.mx.ObtenerMovimientosConciliacionNocturna")
    @ResponseWrapper(localName = "obtenerMovimientosConciliacionNocturnaResponse", targetNamespace = "urn:mx.com.nmp.midas", className = "midas.nmp.com.mx.ObtenerMovimientosConciliacionNocturnaResponse")
    public ArrayOfMovimientoConciliacionNocturna obtenerMovimientosConciliacionNocturna(
        @WebParam(name = "fechaInicio", targetNamespace = "urn:mx.com.nmp.midas")
        XMLGregorianCalendar fechaInicio,
        @WebParam(name = "fechaFin", targetNamespace = "urn:mx.com.nmp.midas")
        XMLGregorianCalendar fechaFin)
        throws ConciliacionPagoOnlineFaultMessage
    ;

    /**
     * 
     * @param fechaFin
     * @param movimientos
     * @param fechaInicio
     * @return
     *     returns boolean
     * @throws ConciliacionPagoOnlineFaultMessage
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "urn:mx.com.nmp.midas")
    @RequestWrapper(localName = "conciliarMovimientos", targetNamespace = "urn:mx.com.nmp.midas", className = "midas.nmp.com.mx.ConciliarMovimientos")
    @ResponseWrapper(localName = "conciliarMovimientosResponse", targetNamespace = "urn:mx.com.nmp.midas", className = "midas.nmp.com.mx.ConciliarMovimientosResponse")
    public boolean conciliarMovimientos(
        @WebParam(name = "fechaInicio", targetNamespace = "urn:mx.com.nmp.midas")
        XMLGregorianCalendar fechaInicio,
        @WebParam(name = "fechaFin", targetNamespace = "urn:mx.com.nmp.midas")
        XMLGregorianCalendar fechaFin,
        @WebParam(name = "movimientos", targetNamespace = "urn:mx.com.nmp.midas")
        ArrayOfMovimientoProveedorTransaccional movimientos)
        throws ConciliacionPagoOnlineFaultMessage
    ;

    /**
     * 
     * @param fecha
     * @return
     *     returns boolean
     * @throws ConciliacionPagoOnlineFaultMessage
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "urn:mx.com.nmp.midas")
    @RequestWrapper(localName = "isDiaHabilConciliacion", targetNamespace = "urn:mx.com.nmp.midas", className = "midas.nmp.com.mx.IsDiaHabilConciliacion")
    @ResponseWrapper(localName = "isDiaHabilConciliacionResponse", targetNamespace = "urn:mx.com.nmp.midas", className = "midas.nmp.com.mx.IsDiaHabilConciliacionResponse")
    public boolean isDiaHabilConciliacion(
        @WebParam(name = "fecha", targetNamespace = "urn:mx.com.nmp.midas")
        XMLGregorianCalendar fecha)
        throws ConciliacionPagoOnlineFaultMessage
    ;

}
