
package midas.nmp.com.mx;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ConciliacionPagoOnlineFaultMessage", targetNamespace = "urn:mx.com.nmp.midas")
public class ConciliacionPagoOnlineFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private mx.com.montedepiedad.servicios.nmp.services.nmpconciliacionpagoonline.ConciliacionPagoOnlineFaultMessage faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ConciliacionPagoOnlineFaultMessage(String message, mx.com.montedepiedad.servicios.nmp.services.nmpconciliacionpagoonline.ConciliacionPagoOnlineFaultMessage faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ConciliacionPagoOnlineFaultMessage(String message, mx.com.montedepiedad.servicios.nmp.services.nmpconciliacionpagoonline.ConciliacionPagoOnlineFaultMessage faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: mx.com.montedepiedad.servicios.nmp.services.nmpconciliacionpagoonline.ConciliacionPagoOnlineFaultMessage
     */
    public mx.com.montedepiedad.servicios.nmp.services.nmpconciliacionpagoonline.ConciliacionPagoOnlineFaultMessage getFaultInfo() {
        return faultInfo;
    }

}
