
package mx.com.nmp.pagos.mimonte.conector.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EstadoCuentaEndpointService", targetNamespace = "http://ws.api.mimonte.ms.nmp.com.mx/", wsdlLocation = "file:/EstadoCuenta.wsdl")
public class EstadoCuentaEndpointService
    extends Service
{

    private final static URL ESTADOCUENTAPOINTSERVICE_WSDL_LOCATION;
    private final static WebServiceException ESTADOCUENTAENDPOINTSERVICE_EXCEPTION;
    private final static QName ESTADOCUENTAENDPOINTSERVICE_QNAME = new QName("http://ws.api.mimonte.ms.nmp.com.mx/", "EstadoCuentaEndpointService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/EstadoCuenta.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ESTADOCUENTAPOINTSERVICE_WSDL_LOCATION = url;
        ESTADOCUENTAENDPOINTSERVICE_EXCEPTION = e;
    }

    public EstadoCuentaEndpointService() {
        super(__getWsdlLocation(), ESTADOCUENTAENDPOINTSERVICE_QNAME);
    }

    public EstadoCuentaEndpointService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ESTADOCUENTAENDPOINTSERVICE_QNAME, features);
    }

    public EstadoCuentaEndpointService(URL wsdlLocation) {
        super(wsdlLocation, ESTADOCUENTAENDPOINTSERVICE_QNAME);
    }

    public EstadoCuentaEndpointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ESTADOCUENTAENDPOINTSERVICE_QNAME, features);
    }

    public EstadoCuentaEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EstadoCuentaEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EstadoCuentaService
     */
    @WebEndpoint(name = "EstadoCuentaEndpointPort")
    public EstadoCuentaService getEstadoCuentaEndpointPort() {
        return super.getPort(new QName("http://ws.api.mimonte.ms.nmp.com.mx/", "EstadoCuentaEndpointPort"), EstadoCuentaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EstadoCuentaService
     */
    @WebEndpoint(name = "EstadoCuentaEndpointPort")
    public EstadoCuentaService getEstadoCuentaEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.api.mimonte.ms.nmp.com.mx/", "EstadoCuentaEndpointPort"), EstadoCuentaService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ESTADOCUENTAENDPOINTSERVICE_EXCEPTION!= null) {
            throw ESTADOCUENTAENDPOINTSERVICE_EXCEPTION;
        }
        return ESTADOCUENTAPOINTSERVICE_WSDL_LOCATION;
    }

}
