
package mx.com.nmp.pagos.mimonte.conector.ws;

import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import mx.com.nmp.pagos.mimonte.conector.ws.datatypes.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EstadoCuentaService", targetNamespace = "http://ws.api.estadocuenta.mimonte.ms.nmp.com.mx/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EstadoCuentaService {


}
