
package mx.com.nmp.pagos.mimonte.conector.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OpenPayEndpointService", targetNamespace = "http://ws.api.mimonte.ms.nmp.com.mx/", wsdlLocation = "file:/OpenPay.wsdl")
public class OpenPayEndpointService
    extends Service
{

    private final static URL OPENPAYENDPOINTSERVICE_WSDL_LOCATION;
    private final static WebServiceException OPENPAYENDPOINTSERVICE_EXCEPTION;
    private final static QName OPENPAYENDPOINTSERVICE_QNAME = new QName("http://ws.api.mimonte.ms.nmp.com.mx/", "OpenPayEndpointService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/OpenPay.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OPENPAYENDPOINTSERVICE_WSDL_LOCATION = url;
        OPENPAYENDPOINTSERVICE_EXCEPTION = e;
    }

    public OpenPayEndpointService() {
        super(__getWsdlLocation(), OPENPAYENDPOINTSERVICE_QNAME);
    }

    public OpenPayEndpointService(WebServiceFeature... features) {
        super(__getWsdlLocation(), OPENPAYENDPOINTSERVICE_QNAME, features);
    }

    public OpenPayEndpointService(URL wsdlLocation) {
        super(wsdlLocation, OPENPAYENDPOINTSERVICE_QNAME);
    }

    public OpenPayEndpointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OPENPAYENDPOINTSERVICE_QNAME, features);
    }

    public OpenPayEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OpenPayEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OpenPayService
     */
    @WebEndpoint(name = "OpenPayEndpointPort")
    public OpenPayService getOpenPayEndpointPort() {
        return super.getPort(new QName("http://ws.api.mimonte.ms.nmp.com.mx/", "OpenPayEndpointPort"), OpenPayService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OpenPayService
     */
    @WebEndpoint(name = "OpenPayEndpointPort")
    public OpenPayService getOpenPayEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.api.mimonte.ms.nmp.com.mx/", "OpenPayEndpointPort"), OpenPayService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OPENPAYENDPOINTSERVICE_EXCEPTION!= null) {
            throw OPENPAYENDPOINTSERVICE_EXCEPTION;
        }
        return OPENPAYENDPOINTSERVICE_WSDL_LOCATION;
    }

}
